name: Verify version & release notes have been updated

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    # paths:
    #   - 'lib/**'
    #   - 'video_player/lib/**'

jobs:

  check-files-changed:
    runs-on: ubuntu-latest
    outputs:
      shoud-verify: ${{ steps.changed-files.outputs.matched_files != '' }}

    steps:
      - id: changed-files
        uses: knu/changed-files@v1
        with:
          paths: |
            'lib/**'
            'video_player/lib/**'

      - name: show changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.changed_files }}"
          echo "Matched files:"
          echo "${{ steps.changed-files.outputs.matched_files }}"
      
  verify-version:
    runs-on: ubuntu-latest
    needs: check-files-changed
    if: ${{ needs.check-files-changed.outputs.shoud-verify }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Ensure pubspec and release notes have been updated"
        uses: danieljimeneznz/ensure-files-changed@v4.1.1
        with:
          require-changes-to: |
            pubspec.yaml
            CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse pubspec.yaml
        id: yaml-version
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: pubspec.yaml

      - name: Print pubspec.yaml version
        run: |
          echo "${{ steps.yaml-version.outputs['version'] }}"

      - name: Fetch previous tag
        id: tag-version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:  
          fallback: 0.0.1

      - name: Display tag version
        run: |
          echo "${{ steps.tag-version.outputs.tag }}"
    
      - uses: dart-lang/setup-dart@v1
      - name: Verify version increase
        id: version-up
        run: |
          cd version_check
          dart pub get
          dart run bin/version_check.dart -p "${{  steps.tag-version.outputs.tag  }}" -n "${{  steps.yaml-version.outputs['version']  }}"
  
